### ISSUE TITLE
Trailing exclamation marks cannot be styled

### ISSUE THREAD

**Issue by tobyjsullivan** [commonmark/commonmark.js#124]
There is a problem where styling on trailing exclamation marks isn't parsed properly. I've encountered this in my own use of `commonmark` but have created a simple reproduction on [try.commonmark.org](http://spec.commonmark.org/dingus/?text=Works%3A%20Hello%20worl**d!**%0A%0AWorks%3A%20Hello%20worl**d**%0A%0AWorks%3A%20Hello%20worl*d!*%0A%0ADoesn%27t%20work%3A%20Hello%20world**!**%0A%0ADoesn%27t%20work%3A%20Hello%20world*!*%0A%0A).

Example:

```md
Hello world**!**
```

In fact, I can apparently reproduce right here on Github:

**Input**

```md
Works: Hello worl**d!**

Works: Hello worl**d**

Works: Hello worl*d!*

Doesn't work: Hello world**!**

Doesn't work: Hello world*!*
```

**Output**

Works: Hello worl**d!**

Works: Hello worl**d**

Works: Hello worl*d!*

Doesn't work: Hello world**!**

Doesn't work: Hello world*!*

**Comment by shoemakerdr** [comment]
[This line](https://github.com/commonmark/commonmark.js/blob/master/lib/common.js#L32) shows that you have to escape exclamation points when they are by themselves:
```
Now works: Hello world**\!**

Now works: Hello world*\!*

```
Now works: Hello world**\!**

Now works: Hello world*\!*

This also still works when not by itself

```
Still works: Hello worl**d!**

Still works: Hello worl*d!*
```
Still works: Hello worl**d!**

Still works: Hello worl*d!*

**Comment by shoemakerdr** [comment]
'!' is an escapable character, so you have to '\' it. See my (try.commonmark.org)[http://spec.commonmark.org/dingus/?text=Works%3A%20Hello%20worl**d%5C!**%0A%0AWorks%3A%20Hello%20worl*d%5C!*%0A%0ADoesn%27t%20work%3A%20Hello%20world**%5C!**%0A%0ADoesn%27t%20work%3A%20Hello%20world*%5C!*%0A%0A]:

```
Still works: Hello worl**d\!**

Still work: Hello worl*d\!*

Now works: Hello world**\!**

Now works: Hello world*\!*
```

**Comment by tobyjsullivan** [comment]
@shoemakerdr This is perfect, thank you. I'll close this issue since this is by design.
