### ISSUE TITLE
table not support ? ?

### ISSUE THREAD

**Issue by mudenglong** [commonmark/commonmark.js#128]
can't parse string like this: 

```
| col1  | col2 | col3 |
|---------|----------------|----------------|
| 1111   | 22222 | 3333 |
```
I print the string in this:  http://spec.commonmark.org/dingus/ 
not work...

**Comment by vyp** [comment]
It's not in the [spec](http://spec.commonmark.org/0.28/). There's a discussion forum for this: https://talk.commonmark.org/t/tables-in-pure-markdown/81
