### ISSUE TITLE
Empty link destination inside angle brackets in reference link definitions

### ISSUE THREAD

**Issue by Crissov** [commonmark/commonmark.js#133]
The spec v0.28 clearly states that [link destinations](http://spec.commonmark.org/0.28/#link-destination) inside angular brackets can be the empty string:

> A link destination consists of either
>
> - a sequence of zero or more characters between an opening `<` and a closing `>` that contains no spaces, line breaks, or unescaped `<` or `>` characters …

[Dingus]/Commonmark.js and cmark do not support this yet, while markdown-it does. The specified behavior may be beneficial for future extensions, e.g. footnotes or info strings for links or general inline markup.

[Dingus]: http://spec.commonmark.org/dingus/?text=%5Blink%20text%5D%5Blabel%5D%0A%0A%5Blabel%5D%3A%20<>%20"title"

**Comment by jgm** [comment]
This seems to work now...
```
% bin/commonmark
[hi](<>)
<p><a href="">hi</a></p>
```
