### ISSUE TITLE
Write Markdown

### ISSUE THREAD

**Issue by EisenbergEffect** [commonmark/commonmark.js#135]
Assuming that I've read some Markdown into the AST, how would I write that AST back to Markdown instead of HTML or XML?

**Comment by jgm** [comment]
The C implementation, cmark, has a markdown writer.
This could be used as the basis for a markdown writer
that works with this library, but currently there is none.

+++ Rob Eisenberg [Jan 04 18 22:58 ]:

**Comment by EisenbergEffect** [comment]
;( My current problem might be better addressed with some regex transforms rather than the AST then. Thanks for letting me know! I'll leave this open in case you all want to use it to track a potential Markdown writer in the future.
