### ISSUE TITLE
ESModules

### ISSUE THREAD

**Issue by iddan** [commonmark/commonmark.js#136]
[ESModules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) is the standard modules system for JavaScript.

In the web it is supported by all the major latest browsers but most importantly it is interpreted better by bundlers (like Webpack and Rollup) with a technique called Tree Shaking which leverages the static nature of ESModules to eliminate dead code branches.

Implementating it should be easy as

```diff
-exports.name = name
+export { name }
```

```diff
-var name = require('module').name 
+import { name } from './module'
```

This will solve: #65

**Comment by jgm** [comment]
Sorry, I'm not up on the latest JavaScript module technology.
Assuming this will not compromise portability (that would be my biggest concern), would you like to submit a PR?

**Comment by iddan** [comment]
Yeah. It should not compromise portability as there can be a bundled version that can be used as a regular script.

**Comment by daKmoR** [comment]
@jgm is there a possibility to publish a prerelease version of the [esmodule](https://github.com/commonmark/commonmark.js/tree/esmodules) branch?

I would like to see if we can use the es-module version of commonmark directly instead of going through a build 💪

**Comment by nikolas** [comment]
Currently I get an error when trying to import `commonmark` in my React app:

    import commonmark from 'commonmark';

> export 'commonmark' was not found in 'commonmark' 

Will this fix that problem?

**Comment by jgm** [comment]
The esmodules changes have been merged, so this issue can be closed.

@nikolas - as for your issue, what version of commonmark.js are you using?

**Comment by nikolas** [comment]
I'm using the latest - commonmark version 0.29.2.

**Comment by jgm** [comment]
Maybe @iddan, who submitted this PR, can give some guidance?

**Comment by iddan** [comment]
@nikolas can you try:
```javascript
import * as commonmark from "commonmark"
```

**Comment by marcoswebdev** [comment]
I tried this:

> ```js
> import * as commonmark from "commonmark"
> ```
 And got:
```sh
SyntaxError: The requested module '../../mdurl/encode.js' does not provide an export named 'default'
```

**Comment by nikolas** [comment]
@iddan thank you, that solves the issue for me. This could be on the readme, as anyone using commonmark in webpack will need to know how to import it like this.

**Comment by jgm** [comment]
I could really use suggestions from people who actually use JavaScript as to how to word a note in the README.
I gather from @marcoswebdev's comment that the thing that worked for you won't work in every context; we need advice for all the different ways one might use the library, perhaps?
