### ISSUE TITLE
Explicit line break with backslash should constitute a word boundary

### ISSUE THREAD

**Issue by Crissov** [commonmark/commonmark.js#137]
As mentioned twice on the Commonmark Discourse, in [2736](https://talk.commonmark.org/t/odd-behaviour-with-colon-emphasis-and-linebreak/2736) and [2695](https://talk.commonmark.org/t/emphasis-delimiter-parsing-difference-with-hard-linebreaks/2695), `commonmark.js` handles forced line breaks with backslash differently from ones with double space at the end of the line. This differs from all other reference implementations and therefore is a bug.

## Testcase 1
~~~~ markdown
_text_\
next line

*text*\
next line
~~~~
- Result: underscore emphasis is not recognized
- Expectation: same output for both paragraphs

[Dingus](http://spec.commonmark.org/dingus/?text=*foo*%5C%0Abar%0A%0A_foo_%5C%0Abar%0A%0A*foo*%20%20%0Abar%0A%0A_foo_%20%20%0Abar%0A)
[Babelmark 3](https://babelmark.github.io/?text=*foo*%5C%0Abar%0A%0A_foo_%5C%0Abar%0A%0A*foo*%20%20%0Abar%0A%0A_foo_%20%20%0Abar%0A)

## Testcase 2
~~~~ markdown
*text:*\
next line

*text:*  
next line
~~~~
- Result: emphasis before backslash is not recognized
- Expectation: same output for both paragraphs

[Dingus](http://spec.commonmark.org/dingus/?text=*foo%3A*%5C%0Abar%0A%0A_foo%3A_%5C%0Abar%0A%0A*foo%3A*%20%20%0Abar%0A%0A_foo%3A_%20%20%0Abar%0A)
[Babelmark 3](https://babelmark.github.io/?text=*foo%3A*%5C%0Abar%0A%0A_foo%3A_%5C%0Abar%0A%0A*foo%3A*%20%20%0Abar%0A%0A_foo%3A_%20%20%0Abar%0A)

**Comment by jgm** [comment]
Agreed, it's a bug.

**Comment by jgm** [comment]
I now get the same output for both paragraphs, so it seems this has been fixed.
Can it be closed?
