### ISSUE TITLE
documentation of parser vs. renderer options

### ISSUE THREAD

**Issue by FND** [commonmark/commonmark.js#138]
Thanks for this library; it is very useful indeed!

The current docs on `smart` typography (e14e2cbbbb6b941a22330c1e3056952b96799dcf) seem to suggest that this is a renderer option:

```javascript
var reader = new commonmark.Parser();
var writer = new commonmark.HtmlRenderer({ smart: true, safe: true });
```

However, turns out that this doesn't actually work, as it is in fact a parser option:

```javascript
var reader = new commonmark.Parser({ smart: true });
var writer = new commonmark.HtmlRenderer({ safe: true });
```

(I only figured this out by checking the tests.)

It would be useful if we could separate the options into two lists, to spare others similar confusion, e.g.

> `Parser` supports these options: …

> Both `HtmlRenderer` and `XmlRenderer` support the following options: …

**Comment by jgm** [comment]
Good suggestions.  Want to prepare a PR?

**Comment by FND** [comment]
Gladly: Let's continue in #139 then.
