### ISSUE TITLE
Incorrect closing sourcepos column for code blocks 

### ISSUE THREAD

**Issue by oampo** [commonmark/commonmark.js#141]
The `sourcepos` attribute for code blocks reports the column number for the line _before_ the end of the block.

Here's a quick test case:

```js
const commonmark = require('commonmark');
const parser = new commonmark.Parser();

// Annotated with line numbers
// 1 ```
// 2 hello world
// 3 ```
const md = '```\nhello world\n```';

const node = parser.parse(md);

const walker = node.walker();

while ((event = walker.next())) {
    const {node} = event;
    if (node.type === 'code_block') {
        console.log(node.sourcepos);
    }
}
```

I'd expect to see `[[1, 1], [3, 3]]` - the backticks start at L1C1 and end at L3C3.  Instead, I see `[[1, 1], [3, 11]]`, where the closing column number (11) is the length of the `hello world` line before the closing backticks.

**Comment by SonyaOrlova** [comment]
i have the same problem with comments (html block)
example:
```
# Example
<!-- this is a comment -->
```
for the comment i expect to see the following sourcepos `[2, 1] [2, 26]`, but i get ``[2, 1] [2, 9]`

adding `this.lastLineLength = ln.length;` before `this.finalize` here https://github.com/commonmark/commonmark.js/blob/ffc5d8744fc8378379802797302b9125f3ffe66b/lib/blocks.js#L772 solves the problem

**Comment by jgm** [comment]
Thanks for reporting!
