### ISSUE TITLE
Questions on softbreak and autolink

### ISSUE THREAD

**Issue by jiyinyiyong** [commonmark/commonmark.js#146]
I'm using the npm package of commonmark in my [toy project](https://github.com/jiyinyiyong/saw-your-imprint/tree/dev) and got some questions:

* VS Code tells me that `softlink: "<br/>"` is not supported in renderer. The README on npm says it supports "softlink".
* I saw links not highlighted in my project, it's like autolink not working. I found no options related to this.

The npm package was related "a year ago" based on the record. Is this package outdated?

**Comment by jgm** [comment]
Jon <notifications@github.com> writes:

> I'm using the npm package of commonmark in my [toy project](https://github.com/jiyinyiyong/saw-your-imprint/tree/dev) and got some questions:
>
> * VS Code tells me that `softlink: "<br/>"` is not supported in renderer. The README on npm says it supports "softlink".

You mean "softbreak"?  That could be your problem.

> * I saw links not highlighted in my project, it's like autolink not working. I found no options related to this.

Sorry, you need to give a minimal working example to
reproduce the issue you're having, or we can't really
help.

**Comment by jgm** [comment]
If by autolink you mean bare URLs being turned into links, that's not in the commonmark spec and this implementation doesn't support it. You might try markdown-it instead.

**Comment by jiyinyiyong** [comment]
> You mean "softbreak"?  That could be your problem.

I mean there's inconsistency in the npm packages and its type definition in TypeScript. Although that package is not maintained by you probably...

> If by autolink you mean bare URLs being turned into links, that's not in the commonmark spec and this implementation doesn't support it. You might try markdown-it instead.

Thanks. That makes sense. Can I add it by customizing with APIs provided by commonmark?

**Comment by jgm** [comment]
Jon <notifications@github.com> writes:

>> You mean "softbreak"?  That could be your problem.
>
> I mean there's inconsistency in the npm packages and its type definition in TypeScript. Although that package is not maintained by you probably...

No, I no knowing about that.  Maybe there's somewhere
else you can report this?

>> If by autolink you mean bare URLs being turned into links, that's not in the commonmark spec and this implementation doesn't support it. You might try markdown-it instead.
>
> Thanks. That makes sense. Can I add it by customizing with APIs provided by commonmark?

Probably.  You could use the walker API as described
in the README to iterate over text nodes and convert
them to link nodes if they match a URL regex.
