### ISSUE TITLE
Rendering iframe in a code block as text and not html

### ISSUE THREAD

**Issue by JohannBlake** [commonmark/commonmark.js#147]
I would like to render the iframe tag inside a code block - a code block starting and ending with ``` but I haven't been able to do this. It generates an actual iframe. Fortunately, it does strip out the http or https from the iframe's src attribute. What I want is for the iframe to appear as text, which would be the case where a developer may want to explain how to use the iframe. So for example, it would look like this:

```
<iframe src="https://www.google.com />
```

I currently have the *safe* option set to true.

**Comment by jgm** [comment]
I'm not sure I understand what you're trying to do.
Could you give the exact HTML you wish to produce?
commonmark will treat anything between the code
backticks as literal text, not as a tag.
