### ISSUE TITLE
Update spec request to support mixed bold / italics

### ISSUE THREAD

**Issue by Havunen** [commonmark/commonmark.js#148]
Hey

I'm not sure if this is the correct place to post this issue.

Is there any chance to update the markdown specification to support mixed bold / italics. I was building WYSIWYG rich text editor which uses markdown as its data format in REST API. This issue arises when you start mixing bold and italic fonts.

For example,

I want to style a word so that first 3 characters are bold, last 3 characters are bold and then everything from second character till second last character is italic.

This case seems to fail in all markdown parser I found.

Links:

[Markdown-it](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22%23%20This%20is%20bug%20report%5Cn%5CnI%20want%20to%20style%20word%20emphasis%20so%20that%20first%203%20characters%20are%20bold%20and%20last%203%20characters%20are%20bold%5Cn%5CnThen%20from%20the%20second%20first%20character%20make%20italic%20until%20second%20last%20character%5Cn%5CnUsing%20%60_%60%20as%20italic%20separator%20it%20does%20not%20work%3A%5Cn%5Cn%2A%2AE_mp_%2A%2A_ha_%2A%2A_si_s%2A%2A%5Cn%5CnUsing%20%60%2A%60%20as%20italic%20separator%20it%20does%20not%20work%20either%3A%5Cn%28ha%29%20should%20not%20be%20bold%5Cn%5Cn%2A%2AE%2Amp%2A%2A%2A%2Aha%2A%2A%2A%2Asi%2As%2A%2A%5Cn%5CnWhen%20strikethrough%20is%20used%20in%20place%20of%20italic%20it%20works%20as%20expected%5Cn%5Cn%5Cn%2A%2AE~~mp~~%2A%2A~~ha~~%2A%2A~~si~~s%2A%2A%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Afalse%2C%22typographer%22%3Afalse%2C%22_highlight%22%3Afalse%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

[CommonMark dingus](https://spec.commonmark.org/dingus/?text=%23%20This%20is%20bug%20report%0A%0AI%20want%20to%20style%20word%20emphasis%20so%20that%20first%203%20characters%20are%20bold%20and%20last%203%20characters%20are%20bold%0A%0AThen%20from%20the%20second%20first%20character%20make%20italic%20until%20second%20last%20character%0A%0AUsing%20%60_%60%20as%20italic%20separator%20it%20does%20not%20work%3A%0A%23%23%20**E_mp_**_ha_**_si_s**%0A%0AUsing%20%60*%60%20as%20italic%20separator%20it%20does%20not%20work%20either%3A%0A(ha)%20should%20not%20be%20bold%0A%23%23%20**E*mp****ha****si*s**%0A%0AWhen%20strikethrough%20is%20used%20in%20place%20of%20italic%20it%20works%20as%20expected%0A%0A%23%23%20**E~~mp~~**~~ha~~**~~si~~s**)

[Marked](https://marked.js.org/demo/?text=%23%20This%20is%20bug%20report%0A%0AI%20want%20to%20style%20word%20emphasis%20so%20that%20first%203%20characters%20are%20bold%20and%20last%203%20characters%20are%20bold%0A%0AThen%20from%20the%20second%20first%20character%20make%20italic%20until%20second%20last%20character%0A%0AUsing%20%60_%60%20as%20italic%20separator%20it%20does%20not%20work%3A%0A%0A**E_mp_**_ha_**_si_s**%0A%0AUsing%20%60*%60%20as%20italic%20separator%20it%20does%20not%20work%20either%3A%0A(ha)%20should%20not%20be%20bold%0A%0A**E*mp****ha****si*s**%0A%0AWhen%20strikethrough%20is%20used%20in%20place%20of%20italic%20it%20works%20as%20expected%0A%0A**E~~mp~~**~~ha~~**~~si~~s**)

**Comment by jgm** [comment]
This isn't the right place, no. Try
talk.commonmark.org.

But, to answer your qusetion, this will work:
`**E*****emphasi*****s**`

**Comment by Havunen** [comment]
@jgm 

Your example did not work
I want to achieve following word:

<b>E<i>mp</i></b><i>ha</i><b><i>si</i>S</b>
bold - bold and italic - italic - bold and italic - bold

See common mark: https://spec.commonmark.org/dingus/?text=**E*****emphasi*****s**%0A

**Comment by jgm** [comment]
Right. This is tricky but it can be done:

<https://spec.commonmark.org/dingus/?text=first%203%20characters%20are%20bold%2C%20last%203%20characters%20are%20bold%20and%20then%0Aeverything%20from%20second%20character%20till%20second%20last%20character%0Ais%20italic.%0A%0A**a*bc***%3C!--%20--%3E*mno*%3C!--%20--%3E***xy*z**%0A>

Anyway, as noted, this is not the best place for questions like this:  you should ask on https://talk.commonmark.org.  This tracker is for bug reports.

**Comment by jgm** [comment]
Another option is to use a zero-width space:
```
**a*bc***&#x200B;*mno*&#x200B;***xy*z**
```
