### ISSUE TITLE
Corrupted numbering in numeric lists

### ISSUE THREAD

**Issue by unclechu** [commonmark/commonmark.js#150]
```md
1. Blah
2. Meh
421. Blep
1932. Mlem
```
Compiles to:
```md
1. Blah
2. Meh
3. Blep
4. Mlem
```
I was looking for proper example in `0.28` spec to check if that is maybe (but would be weird by my opinion) is correct and expected behavior but didn't find anything.

[Demo on official example compiler](https://spec.commonmark.org/dingus/?text=1.%20Blah%0A2.%20Meh%0A421.%20Blep%0A1932.%20Mlem).
It is also reproduced in stable [Riot](https://riot.im/app/).

**Comment by tulir** [comment]
The spec states that it's intended. 

[Section 5.3, 4th paragraph](https://spec.commonmark.org/0.28/#lists)

> The start number of an ordered list is determined by the list number of its initial list item. **The numbers of subsequent list items are disregarded.**

**Comment by tulir** [comment]
Yeah probably. I think the place for issues/requests about the spec is https://talk.commonmark.org/ or https://github.com/commonmark/CommonMark
