### ISSUE TITLE
Parsing [\\\\\\… takes exponential time

### ISSUE THREAD

**Issue by andersk** [commonmark/commonmark.js#157]
`new commonmark.Parser().parse("[" + "\\".repeat(n))` runs in exponential time:

`[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\` → 1.2 seconds
`[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\` → 1.8 seconds
`[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\` → 2.9 seconds
`[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\` → 4.7 seconds
`[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\` → 7.5 seconds
`[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\` → 12.5 seconds
`[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\` → 20.2 seconds
`[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\` → 32.8 seconds
`[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\` → 52.7 seconds
`[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\` → 83.9 seconds
`[\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\` → 137.8 seconds

This could be a denial of service vulnerability in an application that parses user input.

**Comment by andersk** [comment]
There are also quadratic time cases, like `new commonmark.Parser().parse("[](".repeat(30000))`. (Would you like separate bug reports for these?)

**Comment by jgm** [comment]
Thanks for reporting. cmark (the C reference
implementation) does not seem to have exponential
behavior with this.  That's interesting because the
parsing strategies used are very similar.

**Comment by jgm** [comment]
> There are also quadratic time cases, like `new commonmark.Parser().parse("[](".repeat(30000))`. (Would you like separate bug reports for these?)

I think a separate issue would be appropriate, thanks.
As with the other issue, I don't see quadratic
behavior with cmark, only with commonmark.js.

**Comment by jgm** [comment]
The second case probably has to do with `parseLinkDestination` (handling of nested parens).
