### ISSUE TITLE
Formatting isn't applied if a line ends with exclamation mark, asterisk(s) and backslash

### ISSUE THREAD

**Issue by roythedev** [commonmark/commonmark.js#161]
### Issue

* When ending a formatted text line with "!\*\\",  "!\*\*\\" or  "!\*\*\*\\" the wanted bold, italic or combination formatting isn't applied for backslash forced breaks.
* Escaping the exclamation mark doesn't help.
* Ending the line with two spaces instead of backslashes to add forced breaks works as expected.
* Issue is able to be replicated on https://spec.commonmark.org/dingus/

### Test case (copy to the dingus)

\*\*\*Failed to be bold and italic!\*\*\*\\
text

\*\*Failed to be bold!\*\*\\
text

\*Failed to be italic!\*\\
text

**Comment by jgm** [comment]
Simpler example:
```
*hi!*\!
```
becomes
```
<p>*hi!*!</p>
```

**Comment by jgm** [comment]
I do think this is a parser bug (also in cmark).  The spec says:

> A right-flanking delimiter run is a delimiter run that is (1) not preceded by Unicode whitespace, and either (2a) not preceded by a punctuation character, or (2b) preceded by a punctuation character and followed by Unicode whitespace or a punctuation character. For purposes of this definition, the beginning and the end of the line count as Unicode whitespace.

So the second `*` in this example should count as right-flanking, assuming that the `\` is considered a punctuation character.  (If we substitute another punctuation character, it works: e.g. `*hi!*@`.)

My guess is that `\` is not being considered a punctuation character, and that is the underlying problem.

**Comment by jgm** [comment]
Clarification:  cmark gets `*hi!*\!` right but fails on the orginal case with the escaped newline.
commonmark.js gets both wrong.
