### ISSUE TITLE
Zero-width-character-escaped double-asterisk sequence is not ignored, whereas zero-width-character-escaped single asterisk is

### ISSUE THREAD

**Issue by haqer1** [commonmark/commonmark.js#174]
E.g.:
<pre>
***Essai** 57* :

Ligne 2.

2 ​* 3 ​* 4 = 20

Some langs treat this as equivalent of ^: 2 ​*​* 3 ​*​* 4 = 4096

37e ***chose* *très* importante**.
</pre>

Just wondering if this is considered an issue or not (and if so why it is OK to be different for single vs. double asterisk).
Logged the same at markdown-it, which seems to behave the same way in this regard: https://github.com/markdown-it/markdown-it/issues/607

**Comment by haqer1** [comment]
To clarify, double asterisk in the example above disappears in HTML rendered.

**Comment by jgm** [comment]
If I understand correctly, you a zero-width character between the two asterisks.

- Which character is it?
- Why do you have it there?

**Comment by haqer1** [comment]
> If I understand correctly, you a zero-width character between the two asterisks.

In front of each of the two. 
>     * Which character is it?

E.g.:
<pre>
var s110="***Essai** 57* :\n Ligne 2.\n2 ​* 3 ​* 4 = 20\nSome langs treat this as equivalent of ^: 2 "
 + String.fromCharCode(8203)+ '*' + String.fromCharCode(8203)+ "*" + " 3 " + String.fromCharCode(8203)+ "*" 
   + String.fromCharCode(8203)+ "* 4 = 4096\nUne ***chose* *très* importante**.";
</pre>
>     * Why do you have it there?
I was playing with escaping asterisk.

P.S. Escaping seems to be the weak link in Markdown, which could make one question whether it's worth using it when only a limited set of HTML is involved.

**Comment by jgm** [comment]
The behavior of commonmark.js accords with the spec.  Zero-width space is not "unicode whitespace" according to the spec (because it's not in the Zs category). Hence `* + ZERO_WIDTH_SPACE + *` yields an emphasized ZERO_WIDTH_SPACE rather than a double asterisk.

**Comment by haqer1** [comment]
Actually, it would be more appropriate to compare zero-width-space character with \ character: both seem to escape the following character, but the former seems to not work on when applied to each in a sequence of 2 characters as mentioned in the OP (while it escapes 1 asterisk OK), for instance.

P.S. These kinds of quirks make me question presently whether i should use MD as it is.

**Comment by puzrin** [comment]
@haqer1 if you need quick hack - just replace ZWS with `\` in input, to get behaviour you wish.
