### ISSUE TITLE
Asterisks in URLs are not always ignored (according to specs it seems they should be)

### ISSUE THREAD

**Issue by haqer1** [commonmark/commonmark.js#175]
**E.g.**:
<pre>
Essai 57 : asterisk within a URL 
is not encoded, http://example.com/some/**/*search-phrase*. 37e 
***chose importante***
</pre>

**Result**:
_search-phrase_ is rendered italic (em).

**Expected**:
Apparently HTTP specs say that asterisks are allowed & can serve as delimiters in URLs. Raising the 2 questions IMHO: 
a. should there be an effort to always ignore them in URLs?
b. should this effort be extended to URLs without protocol specified (e.g., even w/o **http://** in example above)?

**Comment by jgm** [comment]
The spec doesn't say anything about bare URLs.  If you want the URL to appear as a link, put it in `<>`.  Some implementations provide an extension for bare URLs, but these extensions always employ heuristics for determining what is in the URL and what is in surrounding punctuation.

Here's what you want:
```
<http://example.com/some/**/*search-phrase*>
```
