### ISSUE TITLE
Specify whether MD implementations should (try to) leave asterisks (and/or underscores) in full bare URLs without protocol or relative bare URLs unencoded when rendering

### ISSUE THREAD

**Issue by haqer1** [commonmark/commonmark.js#176]
E.g.,
<pre>
1. Essai 57 : asterisk within a URL is not encoded, example.com/some/**/*search-phrase*. 37e ***chose importante***.
2. Essai 57 : asterisk within a URL is not encoded, <​example.com/some/**/*search-phrase*​>. 37e ***chose importante***.
3. Essai 57 : asterisk within a URL is not encoded, <​/example/some/**/*search-phrase*​>. 37e ***chose importante***.
</pre>
Note: i added 0-width characters around URL delimiters in examples 2 & 3 only because there weren't shown (in github preview) otherwise. Please delete them if copy-pasting.

Currently, _search-phrase_ is rendered italic in all 3 cases in CM demo. 

P.S. This is a follow up to #175.

**Comment by haqer1** [comment]
Currently asterisks in such URLs have to be escaped as usual (no special treatment), as in:
<pre>
example/some/**/\*search-phrase\*
</pre>

**Comment by haqer1** [comment]
I updated the title to include underscores as well, as in:
<pre>
Essai 57 : asterisk within a URL is not encoded, example/some/**/_search-phrase_. 37e ***chose importante***.
</pre>
Should implementations treat them specially (as well) in such URLs, or require escapes to leave them unencoded while rendering?

**Comment by jgm** [comment]
Special treatment of bare URLs (as distinguished from URLs inside "autolinks," e.g. `<http://example.com>`), is not part of the spec.  This is treated as regular text.

**Comment by haqer1** [comment]
Just for the record, you haven't mentioned the stance on absolute autolinks without protocol specified, or relative autolinks, e.g. as mentioned in points 2. & 3. in the OP (as it stands, asterisk & underlines in these 2 categories are HTML-encoded, whereas in absolute autolinks with protocol specified they aren't (which to some could appear to be an inconsistency)):
<pre>
2. Essai 57 : asterisk within a URL is not encoded, <​example.com/some/**/*search-phrase*​>. 37e ***chose importante***.
3. Essai 57 : asterisk within a URL is not encoded, <​/example/some/**/*search-phrase*​>. 37e ***chose importante***.
</pre>

P.S. These kinds of quirks make me question presently whether i should use MD as it is in a web app. Although, it's definitely attractive for keeping notes, for instance.

**Comment by jgm** [comment]
Look at the spec, you'll see that autolinks in `<...>` are required to have the protocol.
