### ISSUE TITLE
Lowercase `<![cdata[]]>` incorrectly parsed in inlines

### ISSUE THREAD

**Issue by wooorm** [commonmark/commonmark.js#193]
Spec does not mention that lowercase should be ok, rather, to me it reads as if it should not be allowed: https://spec.commonmark.org/0.29/#cdata-section.
The “Block” version of commonmarkjs behaves correctly and does not allow lowercase, but because of the [single regex to parse “inline” html](https://github.com/commonmark/commonmark.js/blob/002ba284d85980c4d57c9d3505a2a4608cecbda2/lib/common.js#L45), it’s allowed.

Input:

```markdown
<![cdata[]]>
```

Yields:

```html
<p><![cdata[]]></p>
```

Expected:

```html
<p>&lt;![cdata[]]&gt;</p>
```

**Comment by esuomi** [comment]
CDATA is defined by the [Extensible Markup Language (XML) 1.0 W3C Recommendation section #2.7](https://www.w3.org/TR/REC-xml/#dt-cdsection) to always start with the static string ` <![CDATA[`, using that exact capitalization.

While not exactly relevant, the why for capitalization is probably a carryover from early times of computing before even ARPANET was a thing; Decades ago when everything was text-based and terminals had a varying levels of features (colors, charsets, row length, bandwidth etc.) one of the neatest tricks to detect feature compatibility automatically was to check username capitalization during login. Computers started as caps only, lowercase came later, so having an user submit their username as lowercase meant a more modern baseline of features for the terminal connection.
