### ISSUE TITLE
Is there a way to decrease size of bundle?

### ISSUE THREAD

**Issue by ArtemAvramenko** [commonmark/commonmark.js#194]
Сompared to the Marked, the size of minimized commonmark,js is more than twice bigger. I see that crucial part of bundle (33 of 73 KB) are entity objects:
```
{Aacute:"Á", aacute:"á",Abreve:"Ă" ... }
```

But in most cases you can use MD without entities. For example outputs for these lines are the same
```
un &eacute;t&eacute; &copy;

un été ©
```

=>

```
<p>un été ©</p>
<p>un été ©</p>
```

Is there a way to build marked.js without entities support?

**Comment by jgm** [comment]
Given the current spec we need this list of entities, and there is no way to build without it.

If entity support were changed in the spec along the lines of #442
https://github.com/commonmark/commonmark-spec/issues/442
then this would no longer be needed.
