### ISSUE TITLE
Sublist start number of "01" not being considered a start number of 1.

### ISSUE THREAD

**Issue by jackdewinter** [commonmark/commonmark.js#207]
Based on a conversation with JGM:

[This](https://johnmacfarlane.net/babelmark2/?text=1.+foo%0A+++1.+bar) results in a list within a list, as it should, but [this](https://johnmacfarlane.net/babelmark2/?text=1.+foo%0A+++01.+bar) results in a single list with the second item being considered part of the starting item's text.

The "starting number" should be 1, and the number "01" should be considered as the number 1, even if the strings are not equivalent.  Please see [this conversation](https://talk.commonmark.org/t/am-i-missing-something-empty-lists-and-html-rendering/3713/5) for more information.

**Comment by 0967622354toon** [comment]
>  #`[]() `
