### ISSUE TITLE
Feature request: equation symbol

### ISSUE THREAD

**Issue by parrotdance** [commonmark/commonmark.js#210]
## Behavior of current version

For now, markdown content like this:
```
$some equations$
```

or like this:
```
$$
some equations
$$
```

will be parsed into node(s) like this:
```javascript
{
    _type: 'text',
    _literal: '$some equations$'
   /* other properties */
}
```
## What I suppose to

For this case:
```
$some equations$
```
or this case:
```
$$
some equations
$$
```
parse them into a **equation node** like this:
```javascript
{
    _type: 'equation', // or 'equation_block'
    _next: [
        {
            _type: 'text',
            _literal: 'some equations',
            /* other properties */
        }
    ]
    /* other properties */
}
```

**Comment by jgm** [comment]
This would be an extension.  Currently commonmark.js is just the reference implementation of the core spec.  If you want extensions, you could look at e.g. markdown-it, which has a math extension.
Another option would be to traverse the AST and convert these text nodes to something else after parsing.

**Comment by parrotdance** [comment]
> Another option would be to traverse the AST and convert these text nodes to something else after parsing.

Yes,  that is the way I currently get through these questions about equation block.

So seems like commonmark.js will never (or temporary) implement features out of core markdown spec? Can I try to extend this feature and make a PR? @jgm

**Comment by jgm** [comment]
Of course you can add the feature, it's open source. But as to whether I'd accept a PR -- right now this project is focused on being the reference implementation, so extensions are out of scope.

**Comment by parrotdance** [comment]
Okay I got that, so I'll close this issue.
