### ISSUE TITLE
Incorrect handling of hard line breaks inside of Link and Image nodes.

### ISSUE THREAD

**Issue by jackdewinter** [commonmark/commonmark.js#211]
Per my discussion on [the forums](https://talk.commonmark.org/t/hard-line-breaks-and-link-reference-definitions/3755): 

# Issue

When I use a single backslash at the end of a line within a Link Reference Definition's link label, it seems to invalidate the entire construct.  However, when 2 spaces are used instead, it parses fine.

# Expected Behavior

Per discussion with @jgm, both these Markdown snippets should provide a link that contains a hard line break in a validly constructed link.

# Discussion

Using 2 space characters at the end of the line in a link:

```Markdown
[  
foo]: /uri

[  
foo]
```

provides the following HTML:

```HTML
<p><a href="/uri"><br />
foo</a></p>
```

However, if I use the blackslash at the end of the line instead of the two space characters:

```Markdown
[\
foo]: /uri

[\
foo]
```

I get:

```HTML
<p>[<br />
foo]: /uri</p>
<p>[<br />
foo]</p>
```

**Comment by jgm** [comment]
cmark gets this right, as does jgm/commonmark-hs.
I need to investigate why the js implementation doesn't.
