### ISSUE TITLE
List Block and HTML Block interaction issue: not handling Type-7 HTML at end properly

### ISSUE THREAD

**Issue by jackdewinter** [commonmark/commonmark.js#213]
Given the following Markdown:

````Markdown
- <script>
- some text
some other text
</script>
````

this implementation returns:

```HTML
<ul>
<li>
<script>
</li>
<li>some text
some other text</li>
</ul>
</script>
```

Based on my reading of the script, [documented here](https://talk.commonmark.org/t/list-block-and-html-block-interaction-help/3777/4), the last three lines should be:

```HTML
some other text
</script></li>
</ul>
```

As the `</script>` tag on line 4 is not a valid HTML Block start (type 7 cannot break paragraphs), it should be considered as normal text, only to be further realized as Raw HTML when processing the inline.

**Comment by jgm** [comment]
I think you're right about this case. commonmark.js and cmark both have this problem.
