### ISSUE TITLE
Possible redos vulnerability

### ISSUE THREAD

**Issue by inf3rno** [commonmark/commonmark.js#215]
The redos checker http://redos-checker.surge.sh/ does not like this regex pattern in your code: https://github.com/commonmark/commonmark.js/blob/master/lib/blocks.js#L36 I don't have time to investigate this further, but it is possible, that this pattern can be attacked and maybe freeze a browser or a server that runs your code by using the proper input string.

**Comment by jgm** [comment]
I simplified the regex in 0af2fcbcc362fb529866d524f6977b4c54de62be
But it still doesn't like it.  I don't see the issue with this one.

**Comment by jgm** [comment]
I have serious doubts about this checker.
It likes
```
(?:\*[ \t]*)
```
but it doesn't like
```
(?:\*[ \t]*){1,1}
```
That makes no sense.

**Comment by inf3rno** [comment]
@jgm I'll try to make a string that triggers it, just a min.

**Comment by inf3rno** [comment]
If you check `/(a*)+$/.test("aaaaaaaaaaaaaaaaaaaaaaaab")` still hangs nodejs. Your pattern is similar to `(xa*)+$`, for that I cannot find a string that is slow, but I am not an expert of the topic, I'll have to think it through.

**Comment by inf3rno** [comment]
I think it is safe, because in the `(xa*)+` the `xaxaxaxaxaxa` strings are not the same as the `xaaaaaaaaaaaa` strings. For `(a*)+` you get `aaaaaaaaaaaa` when you try to repeat the pattern in both cases, that makes it vulnerable. As of the extra `[ \t]*` at the end, it did not matter, I think the regex engine removes it automatically.
