### ISSUE TITLE
Don't parse strings with length of 1 as a list

### ISSUE THREAD

**Issue by alangecker** [commonmark/commonmark.js#219]
This is a followup on https://github.com/matrix-org/matrix-react-sdk/pull/5779.

In chat messages parsed with commonmark within element, we have during conferences quite often the case that people respond non-verbally to spoken content with following messages:
- `+`  _"I support"_
- `-` _"I oppose"_
- `*` _"I want to say something"_

unfortunately all of these 3 messages get rendered to a list with a single empty entry. like:

> *

Because I can't imagine any single character message, where it could be somehow useful to have it treated as markdown, I thought the parsing for these messages can simply be avoided.

In the matrix-react-sdk PR to change that people suggested now that changing this behavior could also be proposed upstream to the commonmark folks.

So, what do you think? :)
should strings of the length of 1 be handled as a simple string instead of a list?
And if yes, any suggestions how implement this?

**Comment by jgm** [comment]
The spec says they're lists. So this library correctly implements the spec.
If you want to raise the issue on talk.commonmark.org, that would be the right place.
But you're talking about a spec change, not a bug in commonmark.js.
