### ISSUE TITLE
Backslash escaping removes new line

### ISSUE THREAD

**Issue by Destroyer** [commonmark/commonmark.js#224]
The following doesn't work as expected
```
hello
\- world
```
when tested on https://spec.commonmark.org/dingus/  it shows the result on one line, ommiting line break. 

As [element](https://github.com/vector-im/element-web/issues/17933) uses commonmark it has the same issue.

**Comment by jgm** [comment]
This has nothing to do with backslash escaping.
By default, line breaks are treated like spaces, so you can hard-wrap text.
If you want them treated as hard breaks instead, the README.md explains how to do that:

> For example, to make soft breaks render as hard breaks in HTML:          
                                                                         
``` js                                                                   
var writer = new commonmark.HtmlRenderer({softbreak: "<br />"});         
```
