### ISSUE TITLE
List tightness is sometimes wrong when a list contains a blockquote

### ISSUE THREAD

**Issue by lexi-lambda** [commonmark/commonmark.js#247]
Consider the following markdown input:

```
* foo
  > bar
  >
  baz
```

Is this list loose or tight? [Here’s what the spec says:](https://spec.commonmark.org/0.30/#loose)

> A list is **loose** if any of its constituent list items are separated by blank lines, or if any of its constituent list items directly contain two block-level elements with a blank line between them. Otherwise a list is **tight**.

This strongly suggests to me that the list should be tight, as it definitely does not *directly* contain two block-level elements with a blank line between them: the blank line is clearly contained in the blockquote. [CommonMark implementations on babelmark3 agree](https://babelmark.github.io/?text=*+foo%0A++%3E+bar%0A++%3E%0A++baz), consistently interpreting the list as tight.

But what if we modify the input slightly? Let’s introduce an inner list:

```
* foo
  > * bar
  >
  baz
```

Surely this should have no impact whatsoever on whether the *outer* list is tight, since we just replaced a paragraph with a list inside the blockquote. But remarkably, [a couple implementations on babelmark3](https://babelmark.github.io/?text=*+foo%0A++%3E+*+bar%0A++%3E%0A++baz), **including commonmark.js**, now interpret the outer list as loose. This seems like a bug.

**Comment by jgm** [comment]
Correct: both should be tight lists (and cmark and commonmark-hs get this right).
So this is a bug in commonmark.js.
