### ISSUE TITLE
How to "re" parse AST to markdown?

### ISSUE THREAD

**Issue by icefery** [commonmark/commonmark.js#248]
## Question
How to "re" parse AST to markdown?

> I'm sorry that I am not very good at English, to find some helpful information from issues seems to be difficult for me.

## Context
I want to `for-each` all the `image` node and migrate images to a new path, which means steps as follow:
1. Parse markdown  to AST
2. Change AST
3. Parse AST to markdown

```js
import { Parser } from 'commonmark'

const md = `![](./image/1.jpg)`
const walker = parser.parse(md).walker()

let event = null
while ((event = walker.next())) {
  if (event.entering && event.node.type === 'image') {
    // move
    const filepath = mv(event.node.destination)
    // change
    event.node.destination = filepath
  }
}

// TODO: How to "re" parse AST to markdown?
```

**Comment by jgm** [comment]
See #83 (open issue).
