### ISSUE TITLE
Closing fence cannot be followed by tabs

### ISSUE THREAD

**Issue by zh4ui** [commonmark/commonmark.js#258]
Hi,

just tested in <https://spec.commonmark.org/dingus/> with the following input:

~~~
```
abc
```````````	
~~~

Notice there is a tab following the closing sequence.

The rendered HTML is :

~~~
<pre><code>abc
```````````	
</code></pre>
~~~

According to <https://spec.commonmark.org/0.30/#fenced-code-blocks>, the tab should not affect the closing sequence, so I figure this is a bug?

**Comment by jgm** [comment]
Yes, thanks for reporting.
