### ISSUE TITLE
Bold formatting breaks after inline HTML

### ISSUE THREAD

**Issue by wlievens** [commonmark/commonmark.js#260]
Entering the following input
```<div style="border: 2px solid purple; display: inline-block; background-color: red; width: 50px; height: 10px;"></div> **test**```

Leaves the "**test**" text unrendered in commonmark.js.

Other other engines do process the text after the HTML element. To me it intuitively seems like they are correct, and this is a bug in commonmark.js, but I did not study any spec documents to assert this.

Comparison:

https://johnmacfarlane.net/babelmark2/?text=%3Cdiv+style%3D%22border%3A+2px+solid+purple%3B+display%3A+inline-block%3B+background-color%3A+red%3B+width%3A+50px%3B+height%3A+10px%3B%22%3E%3C%2Fdiv%3E+**test**%0A

**Comment by jgm** [comment]
This is correct according to the spec.
See https://spec.commonmark.org/0.30/#html-blocks start condition 6.

If you want the text to be interpreted as commonmark, then put a blank line between the raw HTML block and the text.  The spec is designed to give you the flexibility for both possibilities.
