### ISSUE TITLE
List items hard-wrapped to multiple lines

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [commonmark/commonmark.js#265]
This issue may be a confusion caused by my own lack of understanding. If my claim is wrong, please point it out.

## Confirmation of specifications

The list item rule ＃1 says:

> 1. **Basic case.** If a sequence of lines Ls constitute a sequence of blocks *Bs* starting with a character other than a space or tab, and *M* is a list marker of width *W* followed by 1 ≤ *N* ≤ 4 spaces of indentation, then the result of prepending *M* and the following spaces to the first line of Ls*, and indenting subsequent lines of *Ls* by *W + N* spaces, is a list item with *Bs* as its contents. The type of the list item (bullet or ordered) is determined by the type of its list marker. If the list item is ordered, then it is also assigned a start number, based on the ordered list marker.
>
> > https://spec.commonmark.org/0.30/#list-items:~:text=list%20items%3A-,Basic%20case,-.%20If%20a

For this reason, hard-wrapped list items should be properly indented after the second line. The amount of indentation is determined by the sum (*W+N*) of “width of list marker *W*” and “space of indentation *N*”.

In other words, if the indentation amount after the second line is less than *W+N*, the second and subsequent hard-wrapped lines are assumed not to be interpreted as part of the list item.

## Demonstration

Now, as a concrete example, consider hard-wrapping a list like this:

```markdown
-   Hard wrapped text hard wrapped text
```

In this case, *W=1*, *N=3*, so you need to indent *W+N=4* at the beginning of the second and subsequent lines.

So you should type:

```markdown
-   Hard wrapped text
    hard wrapped text
```

This indicates that the indentation amount after the second line should be 4, not 1 or 2. However, commonmark\.js doesn't really seem to reproduce this specification exactly.

I checked the demo.

```markdown
-   Hard wrapped text
hard wrapped text (not indented)
-   Hard wrapped text
 hard wrapped text (indented by one space)
-   Hard wrapped text
  hard wrapped text (indented by two spaces)
-   Hard wrapped text
   hard wrapped text (indented by three spaces)
-   Hard wrapped text
    hard wrapped text (indented by four spaces)
-   Hard wrapped text
     hard wrapped text (indented by five spaces)
```

[Demonstration permalink](https://spec.commonmark.org/dingus/?text=-%20%20%20Hard%20wrapped%20text%0Ahard%20wrapped%20text%20(not%20indented)%0A-%20%20%20Hard%20wrapped%20text%0A%20hard%20wrapped%20text%20(indented%20by%20one%20space)%0A-%20%20%20Hard%20wrapped%20text%0A%20%20hard%20wrapped%20text%20(indented%20by%20two%20spaces)%0A-%20%20%20Hard%20wrapped%20text%0A%20%20%20hard%20wrapped%20text%20(indented%20by%20three%20spaces)%0A-%20%20%20Hard%20wrapped%20text%0A%20%20%20%20hard%20wrapped%20text%20(indented%20by%20four%20spaces)%0A-%20%20%20Hard%20wrapped%20text%0A%20%20%20%20%20hard%20wrapped%20text%20(indented%20by%20five%20spaces))

![har-wrapped unordered list by commonmark.js](https://user-images.githubusercontent.com/75878492/194011923-29f9dd1f-a9ec-42c7-952d-1cd8bee9b5ee.png)

Even though the second line indent of each list item is less than 4, the second and subsequent lines are treated as part of the list item. This is strange and not according to the specification.

Alternatively, you can do it with a ordered list and get similar results. In this case, *W=2*, *N=3*, so *W+N=5* indentation is required.

```markdown
1.   Hard wrapped text
hard wrapped text (not indented)
1.   Hard wrapped text
 hard wrapped text (indented by one space)
1.   Hard wrapped text
  hard wrapped text (indented by two spaces)
1.   Hard wrapped text
   hard wrapped text (indented by three spaces)
1.   Hard wrapped text
    hard wrapped text (indented by four spaces)
1.   Hard wrapped text
     hard wrapped text (indented by five spaces)
```

[Demonstration permalink](https://spec.commonmark.org/dingus/?text=1.%20%20%20Hard%20wrapped%20text%0Ahard%20wrapped%20text%20(not%20indented)%0A1.%20%20%20Hard%20wrapped%20text%0A%20hard%20wrapped%20text%20(indented%20by%20one%20space)%0A1.%20%20%20Hard%20wrapped%20text%0A%20%20hard%20wrapped%20text%20(indented%20by%20two%20spaces)%0A1.%20%20%20Hard%20wrapped%20text%0A%20%20%20hard%20wrapped%20text%20(indented%20by%20three%20spaces)%0A1.%20%20%20Hard%20wrapped%20text%0A%20%20%20%20hard%20wrapped%20text%20(indented%20by%20four%20spaces)%0A1.%20%20%20Hard%20wrapped%20text%0A%20%20%20%20%20hard%20wrapped%20text%20(indented%20by%20five%20spaces))

![hard-wrapped ordered list by commonmark.js](https://user-images.githubusercontent.com/75878492/194011909-55d03c40-bcd6-4a7d-ad04-fb0b8952d4b5.png)

## Expected correct result

For Remark\.js, this rendering is reproduced as per specification.

- Unordered list

    ![hard-wrapped unordered list by Remark.js](https://user-images.githubusercontent.com/75878492/194011234-05b4a47f-0913-4db6-8dcc-7acc84a30408.png)

- Ordered list

    ![hard-wrapped ordered list by Remark.js](https://user-images.githubusercontent.com/75878492/194011214-955aef5f-1a6d-4ccc-8126-d4c4b8f42b35.png)

**Comment by jgm** [comment]
See the discussion of "lazy continuation lines."
https://spec.commonmark.org/0.30/#lazy-continuation-line

**Comment by Yarakashi-Kikohshi** [comment]
@jgm, thank you for reply.

I did not understand the "lazy continuation line" in detail and therefore did not understand that the problem I highlighted was due to this.

This has raised some questions for me, but it is not fit to repeat the questions here, so I will close this issue and move on to <https://talk.commonmark.org/>.
