### ISSUE TITLE
Spec Order List needs to update

### ISSUE THREAD

**Issue by devPaulRS** [commonmark/commonmark.js#266]
The spec is outdated for order list.

1. Main item
a. Sub item
b. Sub item
2. Second main item
3. Third main item

GitHub and others works this way, 2 spaces after the line doesnt make sense to workaround this problem.

Example: 
https://spec.commonmark.org/dingus/?text=1.%20This%20is%20the%20main%20item%0Aa.%20This%20is%20a%20sub%20item%20of%20the%20main%20item%0Ab.%20This%20is%20a%20second%20sub%20item%20of%20the%20main%20item%0A2.%20This%20is%20the%20second%20main%20item%0Aa.%20This%20is%20the%20first%20sub%20item%20of%20the%20second%20main%20item%0A3.%20This%20is%20the%20third%20main%20item%0A%0AExpectation%3A%0AThis%20is%20adding%20double%20spaces%20at%20the%20end%20of%20each%20line.%0A%0A1.%20This%20is%20the%20main%20item%20%20%0Aa.%20This%20is%20a%20sub%20item%20of%20the%20main%20item%20%20%0Ab.%20This%20is%20a%20second%20sub%20item%20of%20the%20main%20item%20%20%0A2.%20This%20is%20the%20second%20main%20item%20%20%0Aa.%20This%20is%20the%20first%20sub%20item%20of%20the%20second%20main%20item%20%20%0A3.%20This%20is%20the%20third%20main%20item%20%20%0A

**Comment by vassudanagunta** [comment]
Zero of the parsers [that return results in BabelMark 3](https://babelmark.github.io/?text=1.+This+is+the+main+item%0Aa.+This+is+a+sub+item+of+the+main+item%0Ab.+This+is+a+second+sub+item+of+the+main+item%0A2.+This+is+the+second+main+item%0Aa.+This+is+the+first+sub+item+of+the+second+main+item%0A3.+This+is+the+third+main+item%0A%0AExpectation%3A%0AThis+is+adding+double+spaces+at+the+end+of+each+line.%0A%0A1.+This+is+the+main+item++%0Aa.+This+is+a+sub+item+of+the+main+item++%0Ab.+This+is+a+second+sub+item+of+the+main+item++%0A2.+This+is+the+second+main+item++%0Aa.+This+is+the+first+sub+item+of+the+second+main+item++%0A3.+This+is+the+third+main+item++%0A) behave according to your expectations, including GitHub Flavored Markdown (GFM), Pandoc and CommonMark. Neither does the original Markdown, which you can try here: https://daringfireball.net/projects/markdown/dingus.

In fact, it's not true that this forum or GitHub comments behave as you expect. As you can see in the HTML output shown in your linked CommonMark.js demo, or in the HTML at the above BabelMark 3 link, "a. Sub item" and "b. Sub item" are not actually being parsed or rendered as list items in a sublist of item 1. They are just continuations of item 1's paragraph "Main item", but with hard line breaks in the rendering where there are "[soft line breaks](https://spec.commonmark.org/0.29/#soft-line-breaks)" in the source. As the preceding link explains, soft line breaks within a the paragraph in the source can be rendered as hard or soft line breaks in the output, *at the renderer's discretion*. 

For example:
```
Main item
a. Not really a list item
b. Not really a list item.
33. Still not a list item.
34. Just continuation of the same paragraph with intervening "soft line breaks", which should be evident in the way this "item" soft wraps in the browser rendering. 
```

renders in this forum as:

***
Main item
a. Not really a list item
b. Not really a list item.
33. Still not a list item.
34. Just continuation of the same paragraph with intervening "soft line breaks", which should be evident in the way this "item" soft wraps in the browser rendering. 
***

**Comment by devPaulRS** [comment]
It's fine I'll code it myself, urks me that people are so scared to make better changes.

**Comment by vassudanagunta** [comment]
Urks me that there are people with the arrogance to judge other people as "scared to make better decisions" and assume their own *preferences* and *predilection* are somehow smarter or courageous.

You might want to switch to Asciidoc whose plain text lists behave as you desire. Though I'd be surprised if you don't deem the Asciidoc creators as stupid or cowardly for some other behavior you don't like.

Don't bother with reStructuredText. Apparently they are as dumb and cowardly as the Markdown folks.

Have a nice day.

**Comment by jgm** [comment]
The current behavior *and its motivation* is clearly outlined in the spec.
A different rule would be possible in a markup that doesn't include indented code blocks (for example, my <https://djot.net>).
