### ISSUE TITLE
Incorrect `_` emphasis parsing

### ISSUE THREAD

**Issue by notriddle** [commonmark/commonmark.js#271]
Consider these three example snippets:

    __!_!__
    __!x!__
    **!*!**

And the results they give [in the commonmark dingus](https://spec.commonmark.org/dingus/?text=__!_!__%0A%0A__!x!__%0A%0A**!*!**%0A):

> \_\_!\_!\_\_
>
> <strong>!x!</strong>
>
> <strong>!*!</strong>

I think commonmark.js has a bug here, because the `__` in `__!` is a left-flanking delimiter run. It is followed by a unicode punctuation character (`!`), and it is preceded by the beginning of the line (which is treated as whitespace).

More generally, it seems like, if the second example parses successfully, then the first one must also parse. The spec says that underscores are allowed in the middle of underscore-delimited strong emphasis (it wouldn't be allowed at the beginning or end of the emphasis span, but it's not).

This example was found by differential fuzzing with pulldown-cmark. Corresponding issue: https://github.com/raphlinus/pulldown-cmark/issues/660

**Comment by jgm** [comment]
With this input cmark gives:
```
<p>__!_!__
<strong>!x!</strong>
<strong>!*!</strong></p>
```
which I assume is the same as commonmark.js.

I agree that this looks like a bug in both cmark and commonmark.js (which use the same parsing algorithm).
