### ISSUE TITLE
Some inputs taking long time to parse

### ISSUE THREAD

**Issue by manunio** [commonmark/commonmark.js#273]
Hi, While [fuzzing](https://en.wikipedia.org/wiki/Fuzzing) using [ jazzer.js](https://github.com/CodeIntelligenceTesting/jazzer.js/) (for oss-fuzz) `Parser().parse()` was taking longer than exptected time to parse.

```js

const commonmark = require('./dist/commonmark.js');

console.time("test")
const data = `---
pedaommen-

 >-t<!--
	This is another comm| baz | boParagraph two.

<!-- ntic: true
---

Just a [URL](/url/).

[URL and title](/url/ "title").

[URL and ttle](/url/ "title").

[URL and title](/url/  "title preceded by two spaces").

[URL and title](/url/	"title precede/ "title has spaces afterward"  ).

[URL and title]( e]( /url/has space/ "url has space and title").

[Empty]().`

new commonmark.Parser().parse(data)
console.timeEnd("test")
``` 

```
node test.js
test: 2:35.008 (m:ss.mmm)
```

**Comment by jgm** [comment]
I tried the input
```
---
pedaommen-

 >-t<!--
	This is another comm| baz | boParagraph two.

<!-- ntic: true
---

Just a [URL](/url/).

[URL and title](/url/ "title").

[URL and ttle](/url/ "title").

[URL and title](/url/  "title preceded by two spaces").

[URL and title](/url/	"title precede/ "title has spaces afterward"  ).

[URL and title]( e]( /url/has space/ "url has space and title").

[Empty]().
```
with the  [commonmark dingus](https://spec.commonmark.org/dingus/) and it reported a parse time of 1 ms.

I then tried your program above. It completed in 1.682 ms.

So...I can't reproduce this!  Are you using the latest code from the repository?

**Comment by jgm** [comment]
I couldn't reproduce it with this fuzz.js and timeout file either. Odd!  Can you reproduce it on the online "try commonmark" dingus?

I was using node v18.17.1, but it's hard to imagine that's the issue.

**Comment by jgm** [comment]
OK, I can reproduce it now. I had not regenerated `dist/`, that was the issue.

**Comment by jgm** [comment]
Bisected: the problem starts with commit 28c82d89e6c45e10483b058e06a009ec14312f97 and the next one.
Here's the regex that is causing the problem:
```js
 var HTMLCOMMENT = "<!-->|<!--->|<!--(?:[^-]+|-[^-]|--[^>])*-->"
```

**Comment by jgm** [comment]
OK, I can see why this causes pathological behavior!

**Comment by jgm** [comment]
This should fix it. Thanks for noticing the issue!

**Comment by jgm** [comment]
Sure.

**Comment by jgm** [comment]
cmark output indicates that the input is not UTF-8 encoded.

**Comment by jgm** [comment]
You can post it here, either way.
