### ISSUE TITLE
Im unable to run dingus...

### ISSUE THREAD

**Issue by Kirito-Excalibur** [commonmark/commonmark.js#274]
I opened the repo. 

npm i

make dingus

It then justs passes all the tests and thats it.

**Comment by jgm** [comment]
It should work, giving you output ending with
```
Available on:
  http://127.0.0.1:9000
  http://10.0.0.167:9000
Hit CTRL-C to stop the server
```
You then need to visit that URL.

If it didn't, I'm not sure why. I just tried it and it worked for me.  Take a look at any error output?

**Comment by Kirito-Excalibur** [comment]
![PXL_20231201_172921133.jpg](https://github.com/commonmark/commonmark.js/assets/74639234/9401c010-7617-42db-aef4-5da2ee8a86f8)

This is the error I'm getting

**Comment by jgm** [comment]
Looks like you're using Windows:  I have never tested this Makefile on Windows and I don't assume it would work there.
