### ISSUE TITLE
Do not add the `language-` prefix when the info string already starts with `language-`

### ISSUE THREAD

**Issue by ThomasSoeiro** [commonmark/commonmark.js#277]
commonmark.js adds a `language-` prefix to the info string provided after the opening code fence, regardless if it already starts with `language-`.

Could commonmark.js not adding the `language-` prefix in this case to allow using the `language-` prefix in the source whitout resulting in `language-language-infostring` in html?

E.g., using the following source:

    ```language-r
    x <- 1
    ```
    
    ```r
    x <- 1
    ```

We get the following result:

```html
<pre><code class="language-language-r">x &lt;- 1
</code></pre>
<pre><code class="language-r">x &lt;- 1
</code></pre>
```

---

The commonmark spec currently says that it "does not mandate any particular treatment of the [info string](https://spec.commonmark.org/0.30/#info-string)". A `language-` prefix is added in [example 142](https://spec.commonmark.org/0.30/#example-142).

With `pandoc --from commonmark --to html5 --no-highlight`, we get:

```html
<pre class="language-r"><code>x &lt;- 1</code></pre>
<pre class="r"><code>x &lt;- 1</code></pre>
```

**Comment by ThomasSoeiro** [comment]
@jgm 

Thanks for the fix!

BTW, would you mind releasing a new version? There have been some useful fixes since the last stable release.

**Comment by jgm** [comment]
The changes include changes to spec.txt, so we'd need to do a new release of the spec as well.  Should probably do that, but this is just to let you know why it isn't a trivial thing.
