### ISSUE TITLE
HTML comment handling doesn't match spec 0.31.2?

### ISSUE THREAD

**Issue by robinst** [commonmark/commonmark.js#285]
I'm updating [commonmark-java](https://github.com/commonmark/commonmark-java) to version 0.31.2 of the spec and was wondering about HTML comment handling. Namely, given this spec:

> An [HTML comment](@) consists of `<!-->`, `<!--->`, or  `<!--`, a string of
> characters not including the string `-->`, and `-->` (see the
> [HTML spec](https://html.spec.whatwg.org/multipage/parsing.html#markup-declaration-open-state)).

I think these two should be parsed as comments:

```
foo <!-- test --->
```

```
foo <!-- test ---->
```

However, with the current dingus they're not ([example 1](https://spec.commonmark.org/dingus/?text=foo%20%3C!--%20test%20---%3E), [example 2](https://spec.commonmark.org/dingus/?text=foo%20%3C!--%20test%20----%3E)):

```
<p>foo &lt;!-- test ---&gt;</p>
```

```
<p>foo &lt;!-- test ----&gt;</p>
```

The reason is probably this regex:

https://github.com/commonmark/commonmark.js/blob/a4d859c3ba5794f798d74e181297a94349776336/lib/common.js#L27

I think `<!-->|<!--->|<!--.*?-->` would work as expected.

**Comment by jgm** [comment]
OK, this looks like a holdover from our old XML-ish definition of comment.
Do you want to make  PR?

**Comment by jgm** [comment]
I think cmark may also need to be fixed.
scanners.re has
```
  htmlcomment = "--" ([^\x00-]+ | "-" [^\x00-] | "--" [^\x00>])* "-->";
```

**Comment by robinst** [comment]
> Do you want to make  PR?

Yeah can do later. Do we want some additional examples in the spec as well?
