### ISSUE TITLE
Recognize non-BMP punctuation and symbols

### ISSUE THREAD

**Issue by tats-u** [commonmark/commonmark.js#296]
Current CommonMark.js doesn't recognize non-BMP punctuation and symbols.

https://spec.commonmark.org/dingus/?text=a**a%E2%88%87**a%0A%0Aa**%E2%88%87a**a%0A%0Aa**a%F0%9D%9C%B5**a%0A%0Aa**%F0%9D%9C%B5a**a

```md
a**a∇**a

a**∇a**a

a**a𝜵**a

a**𝜵a**a
```

The last 2 nablas (𝜵) are [U+1D735 Mathematical Bold Italic Nabla](https://www.compart.com/en/unicode/U+1D735).

Expected:

```html
<p>a**a∇**a</p>
<p>a**∇a**a</p>
<p>a**a𝜵**a</p>
<p>a**𝜵a**a</p>
```

Actual:

```html
<p>a**a∇**a</p>
<p>a**∇a**a</p>
<p>a<strong>a𝜵</strong>a</p>
<p>a<strong>𝜵a</strong>a</p>
```

**Comment by tats-u** [comment]
This can be adopted as a test case in the original CommonMark spec.

**Comment by jgm** [comment]
I try to avoid making the spec examples excessively cluttered.  Why not add it to the regression tests for this project?

**Comment by tats-u** [comment]
This bug is very likely to occur in libraries whose platforms use UTF-16 as a string expression.

- markdown-it (I submitted an issue and a PR)
- markdig (it uses char (2 bytes) to check its Unicode category)

Is the regression test shared with many Markdown implementations?

**Comment by tats-u** [comment]
There should be some additional tests other than those as examples in the spec.

JS has Test262 and HTML has Web Platform Tests.
