### ISSUE TITLE
Abstract renderer

### ISSUE THREAD

**Issue by tmpfs** [commonmark/commonmark.js#82]
This issue is to discuss the possibility that the `commonmark` package would supply an abstract renderer and the existing renderers be migrated to specific packages `commonmark-html`, `commonmark-xml` etc.

This would be a breaking change in terms of the API and the README documentation would need to be updated to reflect this change.

A sketch of a possible abstract renderer is here:

https://github.com/tmpfs/mk3/blob/master/lib/render/renderer.js

An improvement would be to use a map for `Types` to save the call to `indexOf`.

The original discussion for this request is in #6.

**Comment by jgm** [comment]
One thing I'm curious about is how it would affect performance to have an abstract renderer + separate html renderer, vs what we have now.

If you build an HTML renderer that can pass the tests, it would be easy to run the benchmarks and compare.

**Comment by tmpfs** [comment]
I would like to know also, I'll tweak the abstract sketch (that `indexOf` is no good) and port the HTML renderer over then we can compare whether the function calls have an impact.

**Comment by tmpfs** [comment]
Wow, I didn't imagine some function calls and property access would hurt so much I am consistently seeing about  200 ops/sec reduction in performance with my quick hack:

https://github.com/tmpfs/commonmark.js

Original renderer:

```
commonmark.js x 1,036 ops/sec ±2.86% (86 runs sampled)
showdown.js x 314 ops/sec ±0.76% (83 runs sampled)
marked.js x 1,083 ops/sec ±1.00% (87 runs sampled)
markdown-it x 979 ops/sec ±2.27% (83 runs sampled)
```

Hacked renderer:

```
commonmark.js x 832 ops/sec ±3.19% (85 runs sampled)
showdown.js x 309 ops/sec ±1.61% (83 runs sampled)
marked.js x 1,101 ops/sec ±1.86% (87 runs sampled)
markdown-it x 1,016 ops/sec ±1.18% (89 runs sampled)
```

Just switch the comment in `index.js` if you want to test on your machine.

I am running a Quad Core 2.67Ghz machine with 8GB RAM.

I think we can still separate the renderers into different packages just need to document that the interface for renderer implementations is `function render(ast)`.

**Comment by tmpfs** [comment]
I suggest that now that `index.js` does not reference the renderers and that they are either required using:

```
var HtmlRenderer = require('commonmark/lib/html');
```

Or if you are willing to move the renderers to the root of the package we could get the slightly cleaner:


```
var HtmlRenderer = require('commonmark/html');
```

Then there is no hassle of managing extra packages in npm. Additional renderers could then be submitted to this repository as pull requests to be reviewed by you.

**Comment by tmpfs** [comment]
BTW, kudos on the test runner built on top of the spec, I know your work is excellent having used `pandoc` but that is very slick! :)

**Comment by jgm** [comment]
node.js optimization is a dark art.  Very small changes can
make a huge difference.

+++ muji [Jan 30 16 04:16 ]:

**Comment by jgm** [comment]
I cloned your repository and I get these benchmarks (similar to yours):
```
jgm@MacBook-Air-2:~/src/tmpfs-commonmark.js % make bench
sudo renice -10 $$; node bench/bench.js bench/samples/README.md
commonmark.js x 589 ops/sec ±9.66% (72 runs sampled)
showdown.js x 196 ops/sec ±6.98% (69 runs sampled)
marked.js x 716 ops/sec ±2.32% (79 runs sampled)
markdown-it x 877 ops/sec ±2.92% (77 runs sampled)

jgm@MacBook-Air-2:~/src/commonmark.js % make bench
sudo renice -10 $$; node bench/bench.js bench/samples/README.md
commonmark.js x 835 ops/sec ±2.20% (90 runs sampled)
showdown.js x 237 ops/sec ±1.53% (88 runs sampled)
marked.js x 731 ops/sec ±1.89% (93 runs sampled)
markdown-it x 904 ops/sec ±2.85% (90 runs sampled)
```
Maybe there's a way to speed things up again.  I'll try to look at the code.

**Comment by jgm** [comment]
I made a few small changes and speeds are back up almost to the original.
```
 % make bench
sudo renice -10 $$; node bench/bench.js bench/samples/README.md
commonmark.js x 824 ops/sec ±2.02% (90 runs sampled)
showdown.js x 229 ops/sec ±2.22% (86 runs sampled)
marked.js x 732 ops/sec ±1.80% (90 runs sampled)
markdown-it x 902 ops/sec ±2.02% (90 runs sampled)
```
You can see the changes I made [here](https://github.com/jgm/commonmark.js/commit/83d88c37be2c9d52d22c522d08975216356205d9).

The main change is that I dropped the lowercasing of method names.  I suppose you're conforming to some norm of JavaScript style that says method names should be lowercase except for constructors?  In that case, perhaps we could just change the internal names of the AST nodes to lowercase.

**Comment by jgm** [comment]
Another alternative is to replace the expensive toLowerCase() with a lookup in a map from the node names to the lowercased method names.  That isn't quite as fast as the version benchmarked above, but it's close.

Q: Do we need to pass the `event` parameter to the methods?  Wouldn't `node` and `entering` suffice?

**Comment by tmpfs** [comment]
> I suppose you're conforming to some norm of JavaScript style that says method names should be lowercase except for constructors?

Exactly that rationale.

> Another alternative is to replace the expensive toLowerCase() with a lookup in a map from the node names to the lowercased method names.

I thought I had already done that, I see it using a lookup in the `Type` map in the latest on master:

https://github.com/tmpfs/commonmark.js/blob/master/lib/render/renderer.js

Ah, but I failed to remove the call to `toLowerCase()`, should be something like:

```javascript
type = Types[event.node.type];
if(!type) {
  throw new Error('Unknown node type ' + event.node.type);
}
``` 

> Do we need to pass the event parameter to the methods?

If we don't lose any potentially pertinent information this is a much cleaner method signature.

If I can get hold of your current branch I'll run the benchmarks on this machine to compare along with the changes we've discussed.

Thanks for taking the time to look at this.

**Comment by tmpfs** [comment]
I have added you as a collaborator to my fork so that you can push that branch without polluting the primary repository, later when we are decided and merged back in I'll delete my fork.

**Comment by tmpfs** [comment]
I think that lowercasing the `type` property simplifies the code dramatically, using CamelCase is good for legibilty with those long switch statements but if we are able to abstract this out to a renderer API without a big performance impact then there is no reason I can see that people need to inspect `type`.

**Comment by tmpfs** [comment]
My bad, I'll just pull down your abstract branch.

Looking at the commit https://github.com/jgm/commonmark.js/commit/83d88c37be2c9d52d22c522d08975216356205d9 I don't actually mind the camelcase methods event though it's not the convention.

**Comment by jgm** [comment]
I wouldn't mind lowercasing the type property.  But if we did this, I think the most non-arbitrary thing to do would be to use the canonical names from the CommonMark.dtd (the ones that appear in the xml output).  These use underscores where we currently have camel case.

``` xml
<!ENTITY % block
         'block_quote|list|code_block|paragraph|heading|thematic_break|html_block|custom_block'>
<!ENTITY % inline
         'text|softbreak|linebreak|code|emph|strong|link|image|html_inline|custom_inline'>
```
How does that sound?  I don't think it would be too hard to make this change to the code.  It would break existing custom filters etc., but I'm not too worried about that since we're still pre-1.0.

**Comment by jgm** [comment]
I can't think of any reason we need `event`, so I already removed it on my branch.

Indeed, instead of passing in `entering` we could have separate methods:
```
enter_block_quote = ...
exit_block_quote = ...
```
and so on.  But non-container nodes like 'Text' don't generate 'exit' events, so it might be awkward to have to remember to use `enter_text` but not `exit_text`.

**Comment by jgm** [comment]
I have pushed a change to my branch that uses the canonical CommonMark.dtd node names (all lowercase).

**Comment by tmpfs** [comment]
On the very latest version of abstract I get these benchmarks:

Original:

```
commonmark.js x 978 ops/sec ±12.69% (87 runs sampled)
showdown.js x 317 ops/sec ±1.92% (83 runs sampled)
marked.js x 1,099 ops/sec ±1.42% (89 runs sampled)
markdown-it x 1,006 ops/sec ±1.86% (86 runs sampled)
```

Abstract:

```
commonmark.js x 883 ops/sec ±3.20% (87 runs sampled)
showdown.js x 321 ops/sec ±0.77% (86 runs sampled)
marked.js x 1,088 ops/sec ±1.07% (88 runs sampled)
markdown-it x 966 ops/sec ±3.08% (83 runs sampled)
```

**Comment by tmpfs** [comment]
>  But if we did this, I think the most non-arbitrary thing to do would be to use the canonical names from the CommonMark.dtd

I like the consistency with the DTD but have always been adverse to underscore delimited names in JavaScript. A little backtrack but something that occured to me just now is: would simple concatenation be expensive?

```javascript
var method = 'on' + event.node.type;
```

Would give us `onText` etc. Whilst we are not using the event emitter API the abstract renderer feels like events to me as the walker encounters the nodes.

> Indeed, instead of passing in entering we could have separate methods:

This I have considered a lot. Initially I liked the idea but tried to keep it simple with the first sketch, thinking about it some more I think there is not a great deal of benefit to having this distinction, although I am guessing it would remove the need for an `entering` parameter.

But it does raise a bigger question, should we have a generic handler for all nodes (`onNode`), this really depends upon the AST. I can't recall a concrete example right now but I remember having to do this for my fork of `marked` to achieve a particular goal. I'll try to find out why.

**Comment by tmpfs** [comment]
I think in terms of maintenance and legibility we should keep the `entering` parameter then all the core logic for each particular node is defined in a single function. This is preferable to me.

Having already removed `event` the method signatures look much cleaner.

**Comment by tmpfs** [comment]
Renderer looks much nicer without the `Types` map; however we should probably document the potential collision because we don't want to check that `typeof(this[type]) === 'function'` that implementations should take care not to do something like `this.link = []` which would generate a runtime error on `link` not being a function.

Using the `on` convention should make this collision less likely.

**Comment by jgm** [comment]
+++ muji [Jan 31 16 20:19 ]:
>     But if we did this, I think the most non-arbitrary thing to do would
>     be to use the canonical names from the CommonMark.dtd
>
>   I like the consistency with the DTD but have always been adverse to
>   underscore delimited names in JavaScript. A little backtrack but
>   something that occured to me just now is: would simple concatenation be
>   expensive?
>
>var method = 'on' + event.node.type;

Tried it.  It is pretty expensive, yes.  You could use a
lookup map instead of concatenating, and that has only a
small (but still significant) performance penalty.

This seems to me a case where a preference for stylistic
consistency shouldn't get in the way of doing the simplist
and most performant thing.  I'm not sure which is worse,
in your view:  having methods that begin with capital
letters like BlockQuote or having methods that contain
underscores?

Of course we could also eliminate the underscores from
the node names, but I think there's good reason to match
the dtd names.

>   But it does raise a bigger question, should we have a generic handler
>   for all nodes (onNode), this really depends upon the AST. I can't
>   recall a concrete example right now but I remember having to do this
>   for my fork of marked to achieve a particular goal. I'll try to find
>   out why.

This would make sense for an xml renderer, since you could
just take the tag name from the node name.  But then, you
could also do this with the straight walker interface.

Would the generic node handler be triggered only if there's
not a more specific one defined?  Or would it go in addition
to a more specific one (before or after)?

**Comment by jgm** [comment]
+++ muji [Jan 31 16 20:28 ]:
>   Renderer looks much nicer without the Types map; however we should
>   probably document the potential collision because we don't want to
>   check that typeof(this[type]) === 'function' that implementations
>   should take care not to do something like this.link = [] which would
>   generate a runtime error on link not being a function.
>
>   Using the on convention should make this collision less likely.

Agreed on both counts.  But I still don't think the on
convention is worth it.

**Comment by tmpfs** [comment]
> Of course we could also eliminate the underscores from the node names, but I think there's good reason to match the dtd names.

I agree with this for the obvious readability reasons of the XML AST documents and given the additional performance hit with following a convention let's go with the most performant and consistent solution, throw convention to the wind :) As you said quite succinctly:

> This seems to me a case where a preference for stylistic consistency shouldn't get in the way of doing the simplist and most performant thing

Let's use underscores.

> Would the generic node handler be triggered only if there's not a more specific one defined? Or would it go in addition to a more specific one (before or after)?

I have just looked at the existing code and my use case as to do with the ordered list problem, maintaining an index and ensuring that ordered lists that were interrupted maintained their index. I think if the AST is modified correctly to fulfill the need to go back to Markdown then this generic `node` method may not be required.

The offending code is here:

https://github.com/tmpfs/markzero/blob/master/lib/render/markdown.js#L57-L79

In that implementation the generic node handler is named `token`.

**Comment by jgm** [comment]
I've merged my abstract branch into master.
More work is still needed (e.g. removing the html renderer from index.js, if that's what we're going to do), but I'm convinced enough of this approach to go forward with it.

**Comment by tmpfs** [comment]
Great! Thanks for being open to the idea.

I have been thinking a lot about how to implement extensions on top of commonmark.js and that this library, should provide a convention for doing it without actually implementing any extensions.

This does not negate the work you have just merged but gives us something to think about, because well we can already do this by walking the AST and performing logic and then passing to a renderer. However, it appears to me that this could likely be achieved with a *single* walk of the AST. Some sorts of post-processing (building TOC etc) would likely need an additional walk, but simple extensions I think could be implemented in a single walk. Clearly, extensions are somewhat coupled to the renderer implementation so starting this work on the renderer is a good move.

I am thinking currently something like:

```
Parser > Iterator > Extensions > Renderer
```

Whereby the `Iterator` is a simple wrapper for the lower-level `Walker` API that just calls the generic `node` handler on the next in the chain (much like the existing renderer logic).

The Extensions would be a class that can have functions plugged in, each function would execute in series for each node encountered in the AST.

My current use case and likely so simple a good place to start is to support `<cite>` from:

```
> Quotation
--Author
```

With or without whitespace after the `--`.

The rules for this are quite simple; does this sound like something worth considering? Is it safe to modify the AST while a walk is executing?

**Comment by tmpfs** [comment]
I am also thinking of something not to different to the node.js streams API but obviously without that dependency so it could still work in the browser. Could we do a lightweight implementation of `pipe` and `write` for the chaining possibly?

**Comment by tmpfs** [comment]
I raise this issue because I see so much discussion about extensions on the forum and I am really keen to see the core specification for Commonmark stay as lightweight as possible, I think we should encourage people to create and contribute extensions for the functionality they need.

**Comment by tmpfs** [comment]
Oh, and extensions will need to create nodes so it would be a good idea to formalize a `createNode` interface rather than having people poking around the source. Or does it already exist?

Thinking about the walker I think it would be safe to modify while walking (without looking at the code - I imagine it just tests for `next` otherwise goes to `parent`), but there might be *rare* cases where an extension might need to backtrack a little (inserting a node before the current node).

**Comment by jgm** [comment]
+++ muji [Feb 07 16 19:52 ]:
>   Oh, and extensions will need to create nodes so it would be a good idea
>   to formalize a createNode interface rather than having people poking
>   around the source. Or does it already exist?

var sourcepos = [[startline, startcol], [endline, endcol]]
var mynode = new Node('strong', sourcepos);

>   Thinking about the walker I think it would be safe to modify while
>   walking (without looking at the code - I imagine it just tests for next
>   otherwise goes to parent), but there might be rare cases where an
>   extension might need to backtrack a little (inserting a node before the
>   current node).

You mean Node.prototype.insertBefore?  It's already there.

**Comment by tmpfs** [comment]
My bad, I edited the comment, wasn't asking about inserting more about backtracking the walker when inserting further up the hierarchy which is provided by `resumeAt` :)

**Comment by tmpfs** [comment]
@jgm, I raised #95 partly because I have some working renderers now that could be folded into commonmark or distributed as a separate module (`commonmark-render` maybe?).

I am still not sure how you want to proceed with this.

So far I have JSON and YAML (which both depend upon the serialization methods in #95) a basic markdown renderer (which is not yet commonmark compliant); a plain text renderer which extends the markdown renderer and resolves links to the form `example[1]` and `[1]: http://example.com`.

I also have a working man page renderer which is not tested yet (unlike the other renderers) but is working quite nicely (I wrote some [TROFF macros](https://github.com/mkdoc/mkout/blob/a0f3eb8aa5ed5e8923eee938fd416e8a51b22d89/lib/man.js#L12-L20) to get six levels of headings and thematic breaks!).

Renderer implementations are here:

https://github.com/mkdoc/mkout/tree/a0f3eb8aa5ed5e8923eee938fd416e8a51b22d89/lib

Documentation on the renderer behaviour is here:

https://github.com/mkdoc/mkout#renderer-implementation

I particularly like the compact YAML view for quickly inspecting and debugging the tree hierarchy.

Let me know what you think about this, should we a) keep the renderers where they are, b) move them to a standalone commonmark renderer package (or individual packages?) or c) integrate them into this repository?

I don't really mind to be honest but I think other people could benefit from having these renderers easily available without depending upon my other libraries.

If you want to integrate with this repository a non-exhaustive list of changes we would need to make:

* Constants for node types
* Static `Node.is()` method
* Static `serialize` and `deserialize` methods
* Exposing `refmap` as discussed (we should expose this data in the XML renderer too!)

**Comment by jgm** [comment]
I'm thinking about these things.  Not much time right now,
but I'll get back to this.

**Comment by cocoademon** [comment]
Hey, sorry to resurrect this, but with the switch to the abstract renderer, `HtmlRenderer().escape` is no longer available programmatically.

I can still get to it by creating an XmlRenderer, but it seems clunky and likely to die when the XML renderer also moves to your abstract/modularized system.

**Comment by tmpfs** [comment]
@jgm, we could expose this on the abstract renderer as:

```javascript
Renderer.prototype.escape = require('../common').escapeXml;
```
Seems reasonable to me, what do you think?

**Comment by jgm** [comment]
+++ muji [Nov 22 16 18:41 ]:
>   [1]@jgm, we could expose this on the abstract renderer as:
>
>Renderer.prototype.escape = require('../common').escapeXml;
>
>   Seems reasonable to me, what do you think?

Problem is that this is xml-specific; the abstract renderer
is supposed to be neutral.

We could add an identity function,

    escape = function(x){ return x};

but note that escapeXml actually takes two arguments.
(One is very xml-specific -- preserveEntities.)

I don't see a very clean way to do this.  Can you not simply
use 'out', which is exposed in the html renderer and does
escaping?

**Comment by cocoademon** [comment]
I can't really use out as I'm generating a table-of-contents during the AST walk (amongst other things).

Is there any philosophical opposition to adding `HtmlRenderer.prototype.escape = esc` to the bottom of lib/render/html.js?

**Comment by tmpfs** [comment]
@cocoademon, as an aside you might want to check out the streaming processing tools I built on top of commonmark.js, you can perform transformations on the AST documents as streams and there is already a module for generating TOC contents.

See [mkdoc](https://github.com/mkdoc/mkdoc) for the entry point and specifically [mktoc](https://github.com/mkdoc/mktoc) for the table of contents generation.

**Comment by jgm** [comment]
+++ Cameron Foale [Nov 23 16 15:14 ]:
>   I can't really use out as I'm generating a table-of-contents during the
>   AST walk (amongst other things).
>
>   Is there any philosophical opposition to adding
>   HtmlRenderer.prototype.escape = esc to the bottom of
>   lib/render/html.js?

My thought is that

- `escape` should be added to the HtmlRenderer prototype
  only if it's added generally (to the abstract Renderer
  prototype); `out` should also then be changed to use
  the renderer's escape function.

- however, there's a problem:  `escape` in the HtmlRenderer
  has two parameters, the second of them very HTML-specific.
  So it's not really clear how you'd add something like
  that coherently to the abstract Renderer.

**Comment by cocoademon** [comment]
Ok, in that case I will continue to use workarounds instead.

@tmpfs Thanks for the links! Super interesting.

**Comment by tmpfs** [comment]
@jgm, I should really migrate the XmlRenderer over to extend the abstract renderer to complete this chunk of work. If I do that and issue a PR against your current HEAD can we get it merged pretty fast?

**Comment by jgm** [comment]
@tmpfs yes, I'll take a look at it quickly anyway!  I'm not sure what all is involved, it has been a while.
But if the idea is that there should be an XmlRenderer and HtmlRenderer should extend that, I agree.  We could then perhaps put an escape function in XmlRenderer.  Maybe it's okay if the more specific renderers have methods that the general Renderer does not?  I don't know about this, as a general point of design.

**Comment by tmpfs** [comment]
My general feeling on the `escape` issue is that it is fine to declare it as an abstract function in the base renderer and leave it up to the concrete sub-class to implement the method. Thinking about it some more nearly every renderer (except possibly plain text) will do some form of escaping.

One exception is the TROFF renderer which does different types of escaping based on a context, in this case we leave it up to the renderer implementation to handle it's escaping requirements.

@jgm, I would like to do the following:

* Declare the abstract `escape` function
* Review the escape implementations (xml and html)
* Improve the formatting (whitespace etc) of the migrated renderers

Does that sound ok to you? I think after this we might be ready to move the renderers into a separate package `commonmark-render` and decouple the rendering from the parser :)

**Comment by jgm** [comment]
+++ muji [Dec 05 16 17:52 ]:
>   My general feeling on the escape issue is that it is fine to declare it
>   as an abstract function in the base renderer and leave it up to the
>   concrete sub-class to implement the method. Thinking about it some more
>   nearly every renderer (except possibly plain text) will do some form of
>   escaping.
>
>   One exception is the TROFF renderer which does different types of
>   escaping based on a context, in this case we leave it up to the
>   renderer implementation to handle it's escaping requirements.
>
>   [1]@jgm, I would like to do the following:
>     * Declare the abstract escape function
>     * Review the escape implementations (xml and html)
>     * Improve the formatting (whitespace etc) of the migrated renderers
>
>   Does that sound ok to you? I think after this we might be ready to move
>   the renderers into a separate package commonmark-render and decouple
>   the rendering from the parser :)

Sounds good (though one has to see the details of course).
